### ISSUE TITLE
Data Library Wiki 

### ISSUE THREAD

**Issue by mbh329** [NYCPlanning/db-data-library#219]
Ideas and thoughts on how to build out the Data Library Wiki:

**Comment by mbh329** [comment]
**- Create a general overview of what data library is:**
- [ ] Essentially a who, what, where, when, why for data library - describe its functionality and purpose within our larger data ecosystem
- [ ] Structure of data library (templates, bash, etc)

**-Overview of library archive **
- [ ] Might be useful to go through an example of updating a "typical" dataset on data library using library archive commands, document the process of how to use library archive, how to check the data is correctly updated on DO, how to properly figure out what file type each dataset uses

**Comment by SashaWeinstein** [comment]
# Sasha's first round of feedback
My overall impression is the new pages are really great. They go over big picture functionality without getting to into the weeds. 
I see some grammatical improvements I can easily make as well 

## Home page
It might be useful to have a broad overview of what data library is. I'm thinking like one sentence for each page in the wiki

## Archive
I think the intro text "Archive function's purpose is moving the s3 bucket" isn't quite detailed enough. Some detail that could be helpful here is that archiving to s3 happens last. It's also a little confusing that it references the ingestor class but the ingestion step also has it's own page. Not something we can fix as it's an issue with data library's design but just wanted to flag

The explanation of how versioning works is super important and it makes sense for it to live here. I can add some more detail to our explanation of versioning, it's quite important 

## Compute
This page is great. Some grammatical stuff to iron out but overall just a very clear writeup of this step. I have two comments
 1. I don't know if we need all the embedded code. I think some could come out, but maybe that's just my preference
 2. Some more detail on the custom scriptor class would be useful, I googled the importlib documentation before I realized that was a local import. The wiki kind of says this but it could be made more clear

## Ingest
Its hard for me to give good feedback here as I don't totally understand the ingest process. Need to put in more time understanding gdal before I can give complete feedback here. There are a couple smaller things I noticed
 - top text block is missing the end of a sentence
 - Instead of "we will not dwell on this here" say "you can read about this in the config page"

**Comment by SashaWeinstein** [comment]
To respond to Max's points:

**who, what, why, where, when** - totally agree

**structure** - I personally see the structure as fairly intuitive and the code as complex so it makes more sense to spend time writing about code. 

**example walkthrough** - think this is great idea

**Comment by td928** [comment]
Hey @mbh329 @SashaWeinstein  I think both of you hit on this and is really on my mind as well. A general roadmap to the entire repo at the home page is really needed before diving into the specific.  I feel like I am kind of ready to do this now because weirdly the big picture was somehow even more elusive than the specifics at first. I will make this my first priority in my next step for this.

**Comment by td928** [comment]
@SashaWeinstein seeing your comment for archive page about versioning I just created another issue about versioning lol #220 which been really bothering me. It would be really great if you could shed some lights on it because I am a little stunned at the moment.

**Comment by SashaWeinstein** [comment]
Sometimes it's better to write introductions last! Gotta go through the details to figure out what you're writing about lol. So not so weird. Will look at issue 220 next

**Comment by mbh329** [comment]
Ditto to @SashaWeinstein - happy to help you draft intro section @td928. Other things worth noting in our wiki might be how poetry shell and docker are used in this repo
